# Identification du projet
sonar.projectKey=Eddy-Mitchel077_SmartTravel
sonar.organization=eddy-mitchel077
sonar.projectName=SmartTravel
sonar.projectVersion=1.0.0

# Source code
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

# Encoding
sonar.sourceEncoding=UTF-8
