name: CI - SmartTravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, Test & Sonar
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Lancer ESLint
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      # 5. Lancer les tests Jest avec coverage
      - name: Run Tests with coverage
        run: npm test -- --coverageReporters=lcov --coverageReporters=text
        continue-on-error: true

      # 6. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true
